### ISSUE TITLE
a

### ISSUE THREAD

**Issue by cxq-haha** [richardhyy/AssemblyLab#1]
请问有电子书么

**Comment by richardhyy** [comment]
不好意思，我这里没有电子书。
这类书籍其实还是建议看纸质版，因为翻阅更方便，且阅读时你的思维可能会更连贯。

--

Sorry, but I do not have the digital edition for this book.
Actually, I highly recommend you read the paper-based book for this kind of book, because it is much more easier to flip through for quick lookup and your mind may be more consistent when reading.
